name = "randomfood"
main = "build/index.mjs"
compatibility_date = "2025-11-10"
account_id = "14d21caaf90af471a0e8f2d520a756ab"
workers_dev = true
send_metrics = true
minify = true
logpush = false

[build]
command = "npm run build"

[triggers]
# crons = ["* * * * *"]

[vars]


# Example environment configuration
# [env.staging]
# name = "randomfood-staging"
# workers_dev = true

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1